### ISSUE TITLE
Add "hacktoberfest" as a topic to the repo so it can be considered as participating

### ISSUE THREAD

**Issue by Tanish2002** [dubesar/GoTutorial#16]
Right now the topics for this repo are `tutorial`, `hacktoberfest-starter` and `hacktoberfest2021` but for hacktoberfest to consider it a legitimate repository it should have a topic named "hacktoberfest".

This topic -> https://github.com/topics/hacktoberfest

**Comment by dubesar** [comment]
Have added.
