### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by dubesar** [dubesar/GoTutorial#7]
Add Go Basic snippets in the readme for all the codes in the current repo ( You can take out the existing codes from the repository )

Snippets includes: 

- [ ] I/O in Go
- [ ] Arrays in Go
- [ ] Maps in Go
- [ ] Functions in Go
- [ ] Pointers in Go
- [ ] Condititons in Go
- [ ] Variables in Go
- [ ] Loops in Go

This should be in the form of small code snippets Not more than 6 lines for each in above list (choose the simplest form to write the above )

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me I'll do it.

**Comment by dubesar** [comment]
@mohitsaxenaknoldus you can start working, this will not be particularly assigned to anyone.

**Comment by mohitsaxenaknoldus** [comment]
Ok thanks! I am on it.

**Comment by Tanish2002** [comment]
Please check my PR.
