### ISSUE TITLE
Add Implementation of Binary Search in Algorithms folder 

### ISSUE THREAD

**Issue by dubesar** [dubesar/GoTutorial#8]
Implement binary search in Go and keep the name of the file as binary_search.go and put it in Algorithms folder

**Comment by SugatoBagchi** [comment]
Hey,

I would like to work on this issue. Can you please assign it to me?

**Comment by dolamanee6122** [comment]
hey @dubesar, I would like to work on this. Please assign this to me?

**Comment by dubesar** [comment]
@SugatoBagchi you can work on this, but please submit a pull request as soon as possible.

**Comment by SugatoBagchi** [comment]
@dubesar On it.

**Comment by dubesar** [comment]
@dolamanee6122 please find other issues as well
